%This scripts creates a confusion matrix out of the labels generated by the
%model for the test images
fileID=fopen('model_labels_2.txt');
%true_label is the cell array for true labels for images
true_label=cell(500,1);
%predicted_labels is the cell array for predicted labels for images by our
%model
predicted_label=cell(500,1);
i=1;
tline = 'random';
while ischar(tline)
    tline = fgets(fileID);
    if(tline~=-1)
        split_array=strsplit(tline,'\t');
        true_label{i}=split_array{2};
        predicted_label{i}=split_array{3};
    end
    i=i+1;
end
fclose(fileID);
confMat=confusionmat(true_label,predicted_label);
%normalize the entries of the matrix to lie between 0 and 1
for i=1:size(confMat,1)
    sum=0;
    for j=1:size(confMat,2)
        sum=sum+confMat(i,j);
    end
    for j=1:size(confMat,2)
        confMat(i,j)=confMat(i,j)/sum;
    end
end
display(confMat)
true=eye(25);
%plotconfusion(true,confMat)
%calculate accuracy
accuracy=0;
for i=1:25
    accuracy=accuracy+confMat(i,i);
end
accuracy=accuracy/25;
display(accuracy)